### ISSUE TITLE
Issues building using build.cmd

### ISSUE THREAD

**Issue by superlogical** [bchavez/RethinkDb.Driver#27]
Hi I've just cloned down the project, and when I try run build.cmd I get the following error

````
Checking Paket version (downloading latest stable)...
Paket.exe 2.50.6 is up to date.
Paket version 2.50.6.0
Skipping resolver for group build since it is already up-to-date
Skipping resolver for group Main since it is already up-to-date
C:\Dev\RethinkDb.Driver\Builder\paket.lock is already up-to-date
0 seconds - ready.
WORKING DIR: C:\Dev\RethinkDb.Driver
Building project with version: LocalBuild
Shortened DependencyGraph for Target zip:
<== zip
   <== dnx
      <== BuildInfo
         <== astgen
            <== restore
               <== Clean
   <== msb
   <== mono

The resulting target order is:
 - Clean
 - restore
 - astgen
 - BuildInfo
 - dnx
 - msb
 - mono
 - zip
Starting Target: Clean
C:\Dev\RethinkDb.Driver\__test\results.xml does not exist.
Deleting contents of C:\Dev\RethinkDb.Driver\__compile
Deleting contents of C:\Dev\RethinkDb.Driver\__package
Finished Target: Clean
Starting Target: restore (==> Clean)
MS NuGet Project Restore
C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe "restore" "C:\Dev\RethinkDb.Driver\Source\RethinkDb.Driver.sln" "-OutputDirectory" "C:\Dev\RethinkDb.Driver\Source\packages"
Task failed with Start of process C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe failed. The system cannot find the file specified
Retry.
C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe "restore" "C:\Dev\RethinkDb.Driver\Source\RethinkDb.Driver.sln" "-OutputDirectory" "C:\Dev\RethinkDb.Driver\Source\packages"
Task failed with Start of process C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe failed. The system cannot find the file specified
Retry.
C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe "restore" "C:\Dev\RethinkDb.Driver\Source\RethinkDb.Driver.sln" "-OutputDirectory" "C:\Dev\RethinkDb.Driver\Source\packages"
Task failed with Start of process C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe failed. The system cannot find the file specified
Retry.
C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe "restore" "C:\Dev\RethinkDb.Driver\Source\RethinkDb.Driver.sln" "-OutputDirectory" "C:\Dev\RethinkDb.Driver\Source\packages"
Task failed with Start of process C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe failed. The system cannot find the file specified
Retry.
C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe "restore" "C:\Dev\RethinkDb.Driver\Source\RethinkDb.Driver.sln" "-OutputDirectory" "C:\Dev\RethinkDb.Driver\Source\packages"
Task failed with Start of process C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe failed. The system cannot find the file specified
Retry.
C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe "restore" "C:\Dev\RethinkDb.Driver\Source\RethinkDb.Driver.sln" "-OutputDirectory" "C:\Dev\RethinkDb.Driver\Source\packages"
Running build failed.
Error:
System.Exception: Start of process C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@76-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.RestorePackageHelper.runNuGet(String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 86
   at Fake.RestorePackageHelper.runNuGetTrial@94.Invoke(Unit unitVar0) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 94
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.RestorePackageHelper.runNuGetTrial(Int32 retries, String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 95
   at Fake.RestorePackageHelper.RestoreMSSolutionPackages(FSharpFunc`2 setParams, String solutionFile) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 189
   at FSI_0005.Build.clo@117-5.Invoke(Unit _arg5) in C:\Dev\RethinkDb.Driver\Builder\build.fsx:line 120
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 484

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Clean      00:00:00.0032554
Total:     00:00:00.0928552
Status:    Failure
---------------------------------------------------------------------
  1) System.Exception: Start of process C:\Dev\RethinkDb.Driver\Builder\tools\NuGet\NuGet.exe failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@76-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.RestorePackageHelper.runNuGet(String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 86
   at Fake.RestorePackageHelper.runNuGetTrial@94.Invoke(Unit unitVar0) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 94
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.TaskRunnerHelper.runWithRetries[a](FSharpFunc`2 f, Int32 retries) in C:\code\fake\src\app\FakeLib\TaskRunnerHelper.fs:line 32
   at Fake.RestorePackageHelper.runNuGetTrial(Int32 retries, String toolPath, TimeSpan timeOut, String args, FSharpFunc`2 failWith) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 95
   at Fake.RestorePackageHelper.RestoreMSSolutionPackages(FSharpFunc`2 setParams, String solutionFile) in C:\code\fake\src\app\FakeLib\RestorePackageHelper.fs:line 189
   at FSI_0005.Build.clo@117-5.Invoke(Unit _arg5) in C:\Dev\RethinkDb.Driver\Builder\build.fsx:line 120
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 484
---------------------------------------------------------------------


C:\Dev\RethinkDb.Driver>
````

**Comment by bchavez** [comment]
Hey there, it looks like an issue resolving `nuget.exe`.... I'll have a fix for you soon.

**Comment by superlogical** [comment]
Cool!

**Comment by bchavez** [comment]
Hi @superlogical ,

I think I've fixed the issue now. You should be able to compile now. Could you try cloning again and see if you can `build`?

The default target is `msb` since `dnx` and `mono` require a tiny bit more setup than a default install of VS.

Let me know if this resolves your issue. Thanks, Brian.

**Comment by bchavez** [comment]
Hey @superlogical , I think this is fixed now, please feel free to re-open the issue if you're still having trouble building out of the box. :+1:

**Comment by superlogical** [comment]
Will try it out today going into work now
